config/routes.rb
Rails.application.routes.draw do

  root 'application#index'
  get '/auth/:provider/callback', to: 'auth#create'

    resources :users, except: :index

    get 'login' => 'auth#new'
    post 'login' => 'auth#login'
    get 'logout' => 'auth#logout'
    get 'about' => 'application#about'

    resources :ideas, only: [:new, :create, :show, :index]

    resources :comments, only: [:new, :create, :show]
    resources :votes, only: [:create]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :author, class_name: 'User'
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
	has_many :votes, as: :votable

  validates :text, :author, :commentable, presence: true

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :creator, class_name: 'User'
  has_many :comments, as: :commentable
  has_many :votes, as: :votable

  validates :title, :description, :creator, presence: true
  validates :title, uniqueness: true

  validates_length_of :title, :maximum => 120, message: "should more succinct here, add the rest to your description!"
  validates_length_of :title, :minimum => 10, message: "needs to be something that describes your idea"

  validates_length_of :description, :minimum => 10, message: "needs more OOOMPH to share your idea"



end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :ideas, foreign_key: :creator_id
	has_many :comments, foreign_key: :author_id
	has_many :votes, foreign_key: :voter_id

	validates :username, :password_hash, presence: true

	validates :username, :email, uniqueness: { case_sensitive: false }
	validates :email, format: {with: /\w+@\w+.\w+/}

  def password
    @_password ||= BCrypt::Password.new(self.password_hash)
  end

  def password=(plaintext)
    @_password = BCrypt::Password.create(plaintext)
    self.password_hash = @_password
  end

  def self.authenticate(user)
    @_user = User.find_by(username: user[:username])
    @_user if @_user && @_user.password == user[:password]
  end

  def self.find_or_create_from_auth_hash(auth_hash)
    if existing_user = where("lower(username) = ?", auth_hash[:info][:nickname].downcase).first
      existing_user.update(
        provider: auth_hash[:provider],
        bio: auth_hash[:info][:description],
        uid: auth_hash[:uid],
        token: auth_hash[:credentials][:token],
        secret: auth_hash[:credentials][:secret],
        profile_image: auth_hash[:info][:image]
      )
      return existing_user
    else
      new_user = create(
        username: auth_hash[:info][:nickname],
        email: auth_hash[:info][:nickname]+"@twitteruser.com",
        bio: auth_hash[:info][:description],
        profile_image: auth_hash[:info][:image],
        password: auth_hash[:uid],
        provider: auth_hash[:provider],
        uid: auth_hash[:uid],
        token: auth_hash[:credentials][:token],
        secret: auth_hash[:credentials][:secret]
      )
      return new_user
    end
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :voter, class_name: 'User'
	belongs_to :votable, polymorphic: true

  validates :voter, :votable, presence: true
  validates :voter, uniqueness: { scope: :votable,
    message: "you can only vote once on this!" }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    redirect_to ideas_path
  end

  def about
  end

  def current_user
    @_current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def find_idea(id)
    Idea.find_by(id: id)
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def new
    render :login
  end

  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = @user.id
    redirect_to ideas_path
  end

  def login
    @user = User.authenticate(params[:user])
    if @user
      session[:user_id] = @user.id
      redirect_to ideas_path
    else
      @errors = "Username and/or Password invalid, try again"
    end
  end

  def logout
    session.delete(:user_id)
    redirect_to root_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  respond_to :html, :js

  def new
    idea_id = params[:idea_id]
    # @commentable_id = params[:commentable_id]
    # @commentable_type = params[:commentable_type]
    render partial: 'new', locals: { idea_id: idea_id }
  end

  def create

    idea = Idea.find_by(id: params[:comment][:commentable_id].to_i)
    # raise params[:comment][:commentable_id].inspect
    new_comment = idea.comments.new(text: comment_params[:text])
    new_comment.author = current_user
    new_comment.author
    if new_comment.save
      redirect_to idea_path(idea)
      # render partial: 'show', locals: { comment: idea_or_comment }, layout: false if idea_or_comment.is_a? Comment
      # render partial: 'show', locals: { idea: idea }, layout: false # if idea_or_comment.is_a? Idea
    else
      redirect_to idea_path(idea) # if idea_or_comment.is_a? Idea
      # redirect_to comment_path(idea_or_comment) if idea_or_comment.is_a? Comment
    end
  end

  private

  ## Dorment for now
  def idea_or_comment
    puts params
    if params[:comment][:commentable_type] == "Idea"
      Idea.find_by(id: params[:comment][:commentable_id])
    elsif params[:comment][:commentable_type] == "Comment"
      Comment.find_by(id: params[:comment][:commentable_id])
    end
  end

  def comment_params
    params.require(:comment).permit(:text, :commentable_id, :commentable_type)
  end

  # def idea_param
  #   params.require(:idea_id)
  # end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
    @ideas = Idea.all
  end

  def new
    @idea = Idea.new
  end

  def create
    new_idea = current_user.ideas.create(idea_params)
    if new_idea.valid?
      redirect_to idea_path(new_idea)
    else
      @errors = new_idea.errors
      render :'new'
    end
  end

  def show
    @idea = find_idea(params[:id]) ## Write helper once views are integrated and we can test
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new()
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to ideas_path
    else
      @errors = @user.errors
      render :'new'
    end
  end

  def show
    puts params
    @user = User.find_by(id: params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :bio)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    new_vote = idea_or_comment.votes.new
    new_vote.voter = current_user
    if new_vote.save
      redirect_to idea_path(params[:idea])
      # render nothing: (true for ajax)
    else
      redirect_to idea_path(params[:idea])
    end
  end

  private

  def idea_or_comment
    if params[:votable_type] == "Idea"
      Idea.find_by(id: params[:votable_id])
    elsif params[:votable_type] == "Comment"
      Comment.find_by(id: params[:votable_id])
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include TweetButton

  TweetButton.default_tweet_button_options = {:via => "TeamYesAnd"}

  def current_user
    @_current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/views/application/about.html.erb
<h1>About YesAnd </h1>
<p>YesAnd is a site to share your ideas and build on the ideas of others. The YesAnd team believes in collaboration and constant feedback as a way to build amazing and useful things, and YesAnd was built to support this method of creation. The concept of "yes and" comes from improv comedy, and represents the practice of taking what a fellow actor gives you and building on it without negating, belittling, or disagreeing with it.</p>
<h1>Team YesAnd</h1>
<p>YesAnd was built as part of our work at <a href='http://devbootcamp.com/'>Dev Bootcamp</a> and created in less than three days.</p>
<div id="us" class="row">
  <div class="small-4 columns">
    <h2>Kara Carrell</h2>
    <p><a href="http://www.twitter.com/KaraAJC">@KaraAJC</a></p>
  </div>
  <div class="small-4 columns">
    <h2>Ricardo Fleury</h2>
    <p><a href="http://www.twitter.com/rfleury2">@rfleury2</a></p>
  </div>
  <div class="small-4 columns">
    <h2>Stephanie Marx</h2>
    <p><a href="http://www.twitter.com/melissid">@melissid</a></p>
  </div>
</div>

app/views/comments/_new.html.erb
<%= form_for :comment, url: comments_path do |f| %>
  <%= f.text_area :text, placeholder: "Yes!! And... " %><br />
  <%= f.hidden_field :commentable_id, :value => idea_id %>
  <%= f.hidden_field :commentable_type, value: @commentable_type %>
  <%= f.submit "Create Comment" %>
<% end %>

app/views/comments/_show.html.erb
<!-- partial, which was a form to create a new comment -->

app/views/ideas/index.html.erb
<!-- main page, list of many ideas, can click on title and/or number of comments to see the idea -->
<!-- <h1>All Ideas</h1> -->
<% if !current_user %>
<br />
  <div class="panel callout radius">
    <h5 id="slogan_title">No idea is a bad idea!</h5>
    <p id="slogan_info">Welcome to <a href='/about'>YesAnd</a>, a site to share your ideas and build on the ideas of others.</p>
  </div>
<% end %>
<ul class="idea_list">
<% @ideas.each do |idea| %>
  <li><%= link_to(idea.title, idea_path(idea)) %>
  <div id="comment-info"> <%= idea.comments.count %> <i class="fa fa-comments"></i></div></li>
<% end %>
</ul>

app/views/ideas/new.html.erb
<!-- create a new idea, has a form for title and body, as well as information about how to create an idea -->
<!-- <h1>Create an Idea</h1> -->
<!-- <em>There will be text here about how to create an idea.</em>
 -->

<%= form_for :idea, url: ideas_path do |f| %>
  <fieldset>
    <legend>Share Your Idea</legend>
  <%= render "shared/errors" %>
  <%= f.label :title, "What's your awesome idea??"%>
  <%= f.text_field :title, placeholder: "Wouldn't it be awesome if...", :required => true %>

  <%= f.label :description, "Tell us all about it!"%>
  <%= f.text_area :description, placeholder: "What makes this idea awesome?", :required => true %>

  <%= f.submit "Create" %>
</fieldset>
<% end %>

app/views/ideas/show.html.erb
<!-- show one idea and all its comments, can upvote main idea and comments, can click to reply to idea or comment, can click on square to see author of idea or comment -->

<% if current_user %>
  <%= button_to("↑ #{@idea.votes.count}", votes_path, params: { votable_id: @idea.id, votable_type: "Idea", idea: @idea.id}, :class => "idea-vote-button") %> <!-- ajax will grab this and create a vote -->
<% end %>


<h1><%= @idea.title %></h1>
<p id="idea-description"><%= @idea.description %> <%= link_to("■", user_path(@idea.creator)) %></p>
<p><%= custom_tweet_button('Tweet This Idea!', {:text => "#{@idea.title} #yesand"}) %></p>

<% if current_user %>
  <p><%= link_to("Yes! And…", new_comment_path(commentable_type: "Idea", commentable_id: @idea.id), remote: true, id: "idea_reply", :"data-current-id" => @idea.id) %></p>
<% end %>

<div class="comments">
  <% @idea.comments.reverse.each do |comment| %>

  <% if current_user %>
    <%= button_to("↑ #{comment.votes.count}", votes_path, params: { votable_id: comment.id, votable_type: "Comment", idea: @idea.id }, :class => "comment-vote-button") %>
    <p><%= comment.text %> <%= link_to("Yes! And…", new_comment_path(commentable_type: "Comment", commentable_id: comment.id), remote: true, class: "comment_reply") %></p>
  <% end %>
  <p><%= comment.text %>
    <% if current_user %>
      <%= link_to("Yes! And…", new_comment_path(commentable_type: "Comment", commentable_id: comment.id), remote: true, class: "comment_reply") %>
    <% end %>
  </p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "YesAnd" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><a href='/'>YesAnd</a></h1>
        </li>
      </ul>

      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <% if session[:user_id] %>
            <li><a id="profile-link" href="<%= user_path(current_user) %>"><%= current_user.username %>'s profile</a></li>
            <li><a href="<%= new_idea_path %>">Share My Idea</a></li>
            <li><a href="/logout">Log Out</a></li>
          <% else %>
            <li><a href="<%= new_user_path %>">Create an Account</a></li>
            <li><a href="/login">Log In</a></li>
          <% end %>
          <li><a href="/about"><i class="fa fa-info-circle fa-2x"></i></a></li>
        </ul>

      </section>
    </nav>
    <div id="content">

    <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if @errors %>
  <% @errors.full_messages.each do |e| %>
  <div class="error"><%= e %></div>
  <% end %>
<% end %>

app/views/users/new.html.erb
<!-- <h1>Create an Account</h1> -->

<%= form_for :user, url: users_path do |f| %>
  <fieldset>
    <legend>Create an Account</legend>
  <%= render "shared/errors" %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :bio %>
  <%= f.text_area :bio %>

  <%= f.submit "Sign Up" %>
<% end %>
  <br />
  <%= button_to('Login via Twitter', '/auth/twitter')%>
  </fieldset>

app/views/users/show.html.erb
<span id="profile">
  <h1><%= image_tag(@user.profile_image, class:"profile_pic") %> | <%= @user.username %></h1>

  <h2>About Me</h2>
  <p id="bio"><%= @user.bio %></p>
  <h2>My Ideas</h2>
  <ul class="idea_list">
  <% @user.ideas.each do |idea| %>
    <li><%= link_to(idea.title, idea_path(idea)) %>
    <div id="comment-info"> <%= idea.comments.count %> <i class="fa fa-comments"></i></div></li>
  <% end %>
  </ul>
  <h2>My Yes Ands</h2>
  <div class="comments">
    <ul>
    <% @user.comments.each do |comment| %>
      <li><%= comment.text %></li>
    <% end %>
  </ul>
  </div>
</span>